### PR TITLE
fix: Hide other sensitive cfg values

### LINKED ISSUE #176: Cache credentials and the private key are exposed in the logs
When the proxy starts, it prints the proxy server config as a log message at info level. If S3 or Redis credentials are used, they are leaked to the logs from that server config. Additionally `SignerPrivateKeyHex` is always leaked regardless of the cache or fallback being used.

```
│ t=2024-10-08T17:28:35+0000 lvl=info msg="Initializing EigenDA proxy server with config: {\n  \"EigenDAConfig\": {\n    \"EdaClientConfig\": {\n      \"RPC\": \"disperser-holesky.eigen │
│ da.xyz:443\",\n      \"StatusQueryTimeout\": 1800000000000,\n      \"StatusQueryRetryInterval\": 5000000000,\n      \"ResponseTimeout\": 60000000000,\n      \"CustomQuorumIDs\": [],\n │
│       \"SignerPrivateKeyHex\": \"REDACTED",\n      \"DisableTLS\": false,\n      \"PutBlobEncodingVersion\": 0,\n      \"Disab │
│ lePointVerificationMode\": false,\n      \"WaitForFinalization\": false\n    },\n    \"VerifierConfig\": {\n      \"KzgConfig\": {\n        \"G1Path\": \"resources/g1.point\",\n       │
│   \"G2Path\": \"\",\n        \"G1PowerOf2Path\": \"\",\n        \"G2PowerOf2Path\": \"resources/g2.point.powerOf2\",\n        \"CacheDir\": \"resources/SRSTables/\",\n        \"NumWor │
│ ker\": 8,\n        \"SRSOrder\": 268435456,\n        \"SRSNumberToLoad\": 524288,\n        \"Verbose\": false,\n        \"PreloadEncoder\": false\n      },\n      \"VerifyCerts\": fal │
│ se,\n      \"RPCURL\": \"\",\n      \"SvcManagerAddr\": \"\",\n      \"EthConfirmationDepth\": 0\n    },\n    \"MemstoreEnabled\": false,\n    \"MemstoreConfig\": {\n      \"MaxBlobSi │
│ zeBytes\": 16777216,\n      \"BlobExpiration\": 1500000000000,\n      \"PutLatency\": 0,\n      \"GetLatency\": 0\n    },\n    \"FallbackTargets\": [],\n    \"CacheTargets\": [],\n    │
│  \"RedisConfig\": {\n      \"Endpoint\": \"\",\n      \"Password\": \"\",\n      \"DB\": 0,\n      \"Eviction\": 86400000000000,\n      \"Profile\": false\n    },\n    \"S3Config\": { │
│ \n      \"CredentialType\": \"static\",\n      \"Endpoint\": \"storage.googleapis.com\",\n      \"EnableTLS\": false,\n      \"AccessKeyID\": \"REDACTED\",\n      \"AccessKeySecret\": \"REDACTED\",\n      \"Bucket\": \"REDACTED\",\n      \"Path\": \"\",\n      │
│  \"Backup\": false,\n      \"Timeout\": 5000000000,\n      \"Profiling\": false\n    }\n  },\n  \"MetricsCfg\": {\n    \"Enabled\": true,\n    \"ListenAddr\": \"0.0.0.0\",\n    \"List │
│ enPort\": 7300\n  }\n}" role=eigenda_proxy
```

### PR DESCRIPTION
**Pull request by epociask**
## Fixes Issue

Fixes #176

### CODE REVIEW

File: cmd/server/entrypoint.go [hunk 1]
```diff
@@ -73,17 +73,15 @@ func StartProxySvr(cliCtx *cli.Context) error {
...
 	// we read a new config which we modify to hide private info in order to log the rest
 	cfg := server.ReadCLIConfig(cliCtx)
-	cfg.EigenDAConfig.EdaClientConfig.SignerPrivateKeyHex = "HIDDEN"
-	cfg.EigenDAConfig.VerifierConfig.RPCURL = "HIDDEN"
-
 	configJSON, err := json.MarshalIndent(cfg, "", "  ")
 	if err != nil {
 		return fmt.Errorf("failed to marshal config: %w", err)
 	}
+	cfg.EigenDAConfig.EdaClientConfig.SignerPrivateKeyHex = "" // marshaling defined in client config
```
Comment (samlaf) [inline cmd/server/entrypoint.go:83]: Why did you move this after the marshaling? Like this it doesn’t do anything

File: store/precomputed_key/redis/redis.go [hunk 2]
```diff
@@ -12,11 +12,10 @@ import (
 
 // Config ... user configurable
 type Config struct {
-	Endpoint string
-	Password string
-	DB       int
-	Eviction time.Duration
-	Profile  bool
+	Endpoint string        `json:"endpoint"`
+	Password string        `json:"-"`
```
Comment (samlaf) [inline store/precomputed_key/redis/redis.go:16]: Nice! Ty!

**Review by samlaf — COMMENTED** [review]
Thanks for this! Just one thing to fix

File: cmd/server/entrypoint.go (hunk 1 above)
Comment (epociask) [reply cmd/server/entrypoint.go:83]: it does actually - the `SignerPrivateKey` is stored as part of the `EigenDAClientConfig` which is defined within layr-labs/eigenda

Comment (samlaf) [reply cmd/server/entrypoint.go:83]: The log line below is
```
log.Info(fmt.Sprintf("Initializing EigenDA proxy server with config: %v", string(configJSON)))
```
which prints the already marshalled config. So changing the fields of cfg here above doesn't do anything.

Comment (epociask) [reply cmd/server/entrypoint.go:83]: 🤦‍♂️

File: store/precomputed_key/redis/redis.go (hunk 2 above)
Comment (samlaf) [inline store/precomputed_key/redis/redis.go:16]: Thought about this approach some more and not sure I like it, for a few reasons:
1) if some future developer ever wants to marshal AND unmarshal the config for whatever reason he will run into a bug (can fix this by defining a custom marshalJSONHideSecrets function instead)
2) this will print empty string, so reader won’t know if password field was hidden or just never set (we can fix this by using omitempty json tag)

Could look something like this (Claude generated so beware):
```
package main

import (
	"encoding/json"
	"fmt"
	"time"
)

type Config struct {
	Endpoint string        `json:"endpoint"`
	Password string        `json:"password,omitempty"`
	DB       int           `json:"database"`
	Eviction time.Duration `json:"eviction"`
}

// Custom MarshalJSON function to control what gets included in the JSON output
func (c Config) MarshalJSON() ([]byte, error) {
	type Alias Config // Use an alias to avoid recursion with MarshalJSON
	aux := struct {
		Alias
		Password string `json:"password,omitempty"`
	}{
		Alias:    (Alias)(c),
		Password: "",
	}

	// Conditionally include a masked password if it is set
	if c.Password != "" {
		aux.Password = "****" // Mask the password instead of excluding it
	}
	return json.Marshal(aux)
}

func main() {
	cfg := Config{
		Endpoint: "localhost:6379",
		Password: "supersecret",
		DB:       0,
		Eviction: time.Hour,
	}

	jsonData, _ := json.MarshalIndent(cfg, "", "  ")
	fmt.Println(string(jsonData))
}
```
Maybe also use a separate Marshal function to not change the default marshaling behavior?

File: cmd/server/entrypoint.go (hunk 1 above)
Comment (samlaf) [reply cmd/server/entrypoint.go]: [53421d7](https://github.com/Layr-Labs/eigenda-proxy/pull/194/commits/53421d71c3e4c96761395078089c3e3c0411a401)

File: store/precomputed_key/redis/redis.go (hunk 2 above)
Comment (samlaf) [reply store/precomputed_key/redis/redis.go]: [4a1404b](https://github.com/Layr-Labs/eigenda-proxy/pull/194/commits/4a1404b42979775ef2b90c09cee1ba2a674a154d)

**Comment by samlaf** [comment]
@epociask @bxue-l2 can you review my fixes. Want to get this merged ASAP, especially before 1.6.0 release.

**Review by bxue-l2 — APPROVED** [review]
