### PR TITLE
fix(#191): Routing namespace --> Storage

### LINKED ISSUE #191: flags: Change `routing` to `storage`

### PR DESCRIPTION
**Pull request by epociask**
## Fixes Issue

Fixes #191

## Changes proposed
- Removed `routing` flag category in favor of `storage`
- Created deprecated flag category for `routing` 
- Introduce store config struct with CLI flags and cfg invariants declared in `/store` package

### CODE REVIEW

File: store/generated_key/memstore/memstore.go [hunk 1]
```diff
@@ -222,16 +222,6 @@ func (e *MemStore) Verify(_, _ []byte) error {
...
 
-// Stats ... returns the current usage metrics of the in-memory key-value data store.
-func (e *MemStore) Stats() *store.Stats {
-	e.RLock()
-	defer e.RUnlock()
-	return &store.Stats{
-		Entries: len(e.store),
-		Reads:   e.reads,
-	}
-}
```
Comment (samlaf) [inline store/generated_key/memstore/memstore.go:233]: Why are you removing this? Was this just not used anymore?

File: flags/eigendaflags/deprecated.go [hunk 2]
```diff
@@ -28,8 +28,8 @@ func withDeprecatedFlagPrefix(s string) string {
 	return "eigenda-" + s
 }
 
-func withDeprecatedEnvPrefix(envPrefix, s string) string {
-	return envPrefix + "_" + s
+func withDeprecatedEnvPrefix(envPrefix, s string) []string {
+	return []string{envPrefix + "_" + s}
```
Comment (samlaf) [inline flags/eigendaflags/deprecated.go:32]: The reason why we had changed this is because returning an array like this prints an ugly msg for deprecated flags. It says something like "flag --routing.xyz (env var [ROUTING.XYZ]) is deprecated"

File: store/cli.go [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+	ConcurrentWriteThreads  = withFlagPrefix("concurrent-write-routines")
+)
+
+func withFlagPrefix(s string) string {
+	return "store." + s
+}
+
+func withEnvPrefix(envPrefix, s string) []string {
+	return []string{envPrefix + "_STORE_" + s}
+}
```
Comment (samlaf) [inline store/cli.go:21]: does singular `store`/`STORE` like this not make it sound like its talking about a single specific store? Just brianstorming here, but what about replacing with either `storage` or `stores` (considered `store_manager` but too long I think)

File: store/deprecated_flags.go [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+func DeprecatedCLIFlags(envPrefix, category string) []cli.Flag {
+	return []cli.Flag{
+		&cli.StringSliceFlag{
+			Name:     DeprecatedFallbackTargetsFlagName,
+			Usage:    "List of read fallback targets to rollover to if cert can't be read from EigenDA.",
+			Value:    cli.NewStringSlice(),
+			EnvVars:  withDeprecatedEnvPrefix(envPrefix, "FALLBACK_TARGETS"),
+			Category: category,
+			Action: func(*cli.Context, []string) error {
+				return fmt.Errorf("flag --%s (env var %s) is deprecated, use --%s (env var %s) instead",
```
Comment (samlaf) [inline store/deprecated_flags.go:37]: (env var %s) will print an array here, consider changing

File: common/store.go
[the remark this answers is not in the document]
Comment (epociask) [reply common/store.go:1]: there was

File: store/generated_key/memstore/memstore.go (hunk 1 above)
Comment (epociask) [reply store/generated_key/memstore/memstore.go:233]: nope - legacy at this point

File: flags/eigendaflags/deprecated.go (hunk 2 above)
Comment (epociask) [reply flags/eigendaflags/deprecated.go:32]: Gotcha - will update

File: store/cli.go (hunk 3 above)
Comment (epociask) [reply store/cli.go:21]: Storage is probably the best fit term for short description of the component abstraction - will update!

File: store/deprecated_flags.go (hunk 4 above)
Comment (epociask) [reply store/deprecated_flags.go:37]: this is done for compliance with the flag declaration - i.e. `StringSliceFlag` --> `[]string` for Action. IIUC its not doing anything with the function params:
```
t=2024-10-29T02:41:26-0400 lvl=crit msg="Application failed" message="flag --routing.cache-targets (env var [EIGENDA_PROXY_CACHE_TARGETS]) is deprecated, use --storage.cache-targets (env var [EIGENDA_PROXY_STORAGE_CACHE_TARGETS]) instead"
```

File: store/cli.go (hunk 3 above)
Comment (epociask) [reply store/cli.go]: [3a6f3fb](https://github.com/Layr-Labs/eigenda-proxy/pull/195/commits/3a6f3fbd9f7ce92bbfe3b98871724bc7b3829a94)

File: flags/eigendaflags/deprecated.go (hunk 2 above)
Comment (epociask) [reply flags/eigendaflags/deprecated.go]: [3a6f3fb](https://github.com/Layr-Labs/eigenda-proxy/pull/195/commits/3a6f3fbd9f7ce92bbfe3b98871724bc7b3829a94)

File: store/cli.go [hunk 5]
```diff
@@ -0,0 +1,59 @@
...
+
+// CLIFlags ... used for Redis backend configuration
```
[the remark this answers is not in the document]
Comment (epociask) [reply store/cli.go]: [3a6f3fb](https://github.com/Layr-Labs/eigenda-proxy/pull/195/commits/3a6f3fbd9f7ce92bbfe3b98871724bc7b3829a94)

File: store/deprecated_flags.go (hunk 4 above)
Comment (samlaf) [reply store/deprecated_flags.go:37]: hmmm that's a good point. I see that you changed them back. Agree with your argument here though! Perhaps we should have used "env varS" with an s then instead... but at this point we're bikeshedding either is fine.

**Review by samlaf — APPROVED** [review]
LGTM!
